-- User identity moves from an app-generated BIGSERIAL to the Keycloak subject (the OIDC "sub"
-- claim, a UUID) - see the Keycloak setup in infra/docker-compose.yml and infra/keycloak/. That
-- id-type change is breaking for every table that referenced the old users.id, so this migration
-- resets the whole user_service schema rather than trying to retrofit each one individually:
--   * alert_rules.user_id is a BIGINT FK to users(id) ON DELETE CASCADE - no longer resolvable
--     once users.id is UUID.
--   * outbox_events.aggregate_id / partition_key are BIGINT columns carrying either a user id or
--     an alert_rule id - can no longer be one BIGINT type once one of those ids is UUID.
-- alert_rules, outbox_events and processed_events all come back in later migrations once their
-- UUID-native shape is worked out (outbox/processed_events specifically - see the design doc
-- sections referenced when this was discussed); not guessed at here.
DROP TABLE outbox_events;
DROP TABLE alert_rules;
DROP TABLE users;

CREATE TABLE users (
    -- The Keycloak subject (JWT "sub" claim) - NEVER generated by this service (no DEFAULT
    -- gen_random_uuid() - the application always supplies it from the validated token). Using the
    -- same id Keycloak already assigned means every other service that only has a user id from a
    -- JWT can use it directly as a foreign reference with no id-mapping lookup anywhere, and ids
    -- are never reused (Keycloak subjects are random UUIDs, never recycled).
    id              uuid        PRIMARY KEY,

    -- Synced from the Keycloak profile (or self-reported) for display/notification purposes.
    -- NOT the identity - id is. TEXT rather than VARCHAR(n): no performance difference in
    -- Postgres, and there's no good reason to invent an arbitrary length cap for an email address.
    email           text        NOT NULL,

    display_name    text        NOT NULL,

    -- IANA timezone id (e.g. 'Europe/Istanbul'), for evaluating alert windows / any future
    -- scheduled reports against the user's local day rather than server UTC. Defaults to 'UTC' so
    -- every row is valid without the client having to supply it on signup.
    timezone        text        NOT NULL DEFAULT 'UTC',

    -- Three-state soft-delete lifecycle instead of a boolean "deleted" flag: deletion is an
    -- asynchronous saga, not an instant DB delete. DELETE /users/me moves ACTIVE -> DELETING;
    -- downstream services (devices, alert rules, ...) react to that and clean up their own data;
    -- a finaliser later moves DELETING -> DELETED once every dependent service has confirmed.
    status          text        NOT NULL DEFAULT 'ACTIVE',

    -- Optimistic-locking column (JPA @Version) - a concurrent UPDATE against a stale version fails
    -- instead of silently overwriting another request's write. Doubles as the event's
    -- aggregateVersion when a change is published, so downstream consumers can tell an event
    -- arrived out of order or is a stale replay.
    version         bigint      NOT NULL DEFAULT 0,

    -- Saga completion flag: set true once the service(s) owning this user's devices confirm
    -- they've finished purging them as part of the deletion saga. The finaliser checks this (and
    -- any future equivalent per-dependency flags) before flipping status to DELETED, so "deleted"
    -- only becomes true once every dependency has actually cleaned up - not just once this row
    -- itself was marked.
    devices_deleted boolean     NOT NULL DEFAULT false,

    -- When DELETE /users/me was called (status moved to DELETING). Drives the grace period and
    -- the finaliser's scan (users_deleting_idx below) for "requested more than <grace> ago, go
    -- finalize". Null for every row that has never had deletion requested.
    deletion_requested_at timestamptz,

    -- When the finaliser actually completed and flipped status to DELETED. Distinct from
    -- deletion_requested_at on purpose - the gap between the two is exactly the grace/cleanup
    -- window. Null until status = 'DELETED' (see users_deleted_consistency_chk).
    deleted_at      timestamptz,

    -- Audit columns. DEFAULT now() covers the initial INSERT; the application keeps updated_at
    -- current on subsequent writes via Hibernate's @UpdateTimestamp (same convention as V2).
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT users_status_chk CHECK (status IN ('ACTIVE','DELETING','DELETED')),

    -- Deliberately cheap, not real email validation (that's Bean Validation's job at the API
    -- boundary) - just a last-resort guard against an obviously-malformed value reaching the DB
    -- some other way (a direct insert, a future backfill script, ...).
    CONSTRAINT users_email_chk  CHECK (position('@' in email) > 1),

    -- Makes "status says DELETED but deleted_at is still null" (or the reverse) impossible at the
    -- DB level. The finaliser and anything downstream can rely on status = 'DELETED' implying
    -- deleted_at is populated, with no defensive null-check needed.
    CONSTRAINT users_deleted_consistency_chk
        CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL))
);

-- Case-insensitive uniqueness (lower()) without needing the citext extension - the application
-- just has to apply lower() consistently on write and on lookup. Partial on status <> 'DELETED':
-- a scrubbed/former account's leftover email must not permanently squat on uniqueness, since this
-- is soft delete, not a real row removal - otherwise the same email could never be re-registered.
CREATE UNIQUE INDEX users_email_uq ON users (lower(email)) WHERE status <> 'DELETED';

-- Serves exactly the finaliser's scan ("DELETING rows whose grace period has elapsed") without a
-- full table scan. Partial on status = 'DELETING' keeps the index small forever - the ACTIVE and
-- DELETED rows that make up the overwhelming majority over time are excluded entirely.
CREATE INDEX users_deleting_idx ON users (deletion_requested_at) WHERE status = 'DELETING';

-- outbox            : reintroduced in a later migration, redesigned for UUID aggregate ids (see §4)
-- processed_events  : reintroduced in a later migration (see §5)
