package com.cagritasoz.user_service.entity;

import com.cagritasoz.user_service.model.UserStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    private UUID id;

    @Column(nullable = false)
    private String email;

    @Column(name = "display_name", nullable = false)
    private String displayName;

    @Builder.Default
    @Column(nullable = false)
    private String timezone = "UTC";

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.ACTIVE;

    @Version
    @Column(nullable = false)
    private Long version;

    @Builder.Default
    @Column(name = "devices_deleted", nullable = false)
    private boolean devicesDeleted = false;

    @Column(name = "keycloak_disabled_at")
    private Instant keycloakDisabledAt;

    @Column(name = "deletion_requested_at")
    private Instant deletionRequestedAt;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    // @Generated -> "This column is generated by the database."
    // Hibernate retrieves the database-generated value after insertion.
    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt;

    // See migration V6 for trigger.
    // Hibernate retrieves the database-generated value after insertion or update.
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private Instant updatedAt;
}